name: Playwright DB Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select browser'
        required: true
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit
      testFile:
        description: "Select the test to run"
        required: true
        type: choice
        options:
          - all
          - sql-schema.test.ts
          - sql-queries.test.ts
          - sql-joins.test.ts
          - sql-excelVal.test.ts
          - etlValidation.test.ts

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    # Define MySQL service
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Tester@08
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=10

    steps:
      #  Checkout repository first
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install MySQL client
      - name: Install MySQL client
        run: sudo apt-get install -y mysql-client

      #  Wait for MySQL service to be ready
      - name: Wait for MySQL
        run: |
          for i in {1..20}; do
            mysqladmin ping -h mysql -uroot -p"Tester@08" &>/dev/null && break
            echo "Waiting for MySQL..."
            sleep 5
          done

      #  Load schemas and data for multiple databases
      - name: Load schemas and data
        run: |
          declare -A DBS
          DBS=( ["sqldb"]="testAssets/testData/sqldb" ["sourcedb"]="testAssets/testData/sourcedb" ["targetdb"]="testAssets/testData/targetdb" )

          for DB in "${!DBS[@]}"; do
            echo "Loading database $DB..."
            SCHEMA_PATH="${DBS[$DB]}/schema.sql"
            DATA_PATH="${DBS[$DB]}/data.sql"

            mysql -h mysql -uroot -p"Tester@08" -e "CREATE DATABASE IF NOT EXISTS $DB;"
            mysql -h mysql -uroot -p"Tester@08" $DB < $SCHEMA_PATH
            mysql -h mysql -uroot -p"Tester@08" $DB < $DATA_PATH
          done

      #  Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      #  Install dependencies
      - name: Install dependencies
        run: npm ci

      #  Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

    

      #  Run Playwright tests
      - name: Run Playwright tests
        continue-on-error: true
        run: npx playwright test --project=chromium

      # Upload Playwright report
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
